<a href="https://colab.research.google.com/github/yrodriguezmd/Fastai_Deep_Learning/blob/main/figuring_out_accuracy_multi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()
from fastbook import *
#!pip install fastai -U
import fastai
from fastai.vision.all import *

     |████████████████████████████████| 720 kB 4.1 MB/s 
     |████████████████████████████████| 188 kB 44.7 MB/s 
     |████████████████████████████████| 1.2 MB 39.5 MB/s 
     |████████████████████████████████| 46 kB 3.6 MB/s 
     |████████████████████████████████| 54 kB 1.8 MB/s 
     |████████████████████████████████| 51 kB 173 kB/s 
Mounted at /content/gdrive


In [ ]:
a = tensor ( [[1,1,1], [1,1,1]] )
b = tensor ( [[1,1,1], [1,1,1]] )

In [ ]:
a

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
def accuracy_multi(inp, targ, thresh = 0.5, sigmoid = True):
    if sigmoid: inp = inp.sigmoid()
    return(( inp> thresh) == targ.bool()).float().mean()

In [ ]:
a = tensor ( [[1,1,1], [1,1,1]] )
b = tensor ( [[1,1,1], [1,1,1]] )

accuracy_multi(a, b)

tensor(1.)

In [ ]:
a = tensor ( [[0,0,0], [0,0,0]] )
b = tensor ( [[1,1,1], [1,1,1]] )

accuracy_multi(a, b)

tensor(0.)

In [ ]:
accuracy_multi(b,a)

tensor(0.)

In [ ]:
a = tensor ( [[1,1,1], [0,0,0]] )
b = tensor ( [[1,1,1], [1,1,1]] )

accuracy_multi(a, b)

tensor(0.5000)

In [ ]:
a = tensor ( [[1,1,1], [1,0,0]] )
b = tensor ( [[1,1,1], [1,1,1]] )

accuracy_multi(a, b)

tensor(0.6667)

In [ ]:
a = tensor ( [[1,1,0], [1,1,0]] )
b = tensor ( [[1,1,1], [1,1,1]] )

accuracy_multi(a, b)

tensor(0.6667)

In [ ]:
accuracy_multi(b,a)

tensor(0.6667)

In [ ]:
a = tensor ( [[1,1,1], [0,0,0]] )
b = tensor ( [[1,1,1], [1,0,0]] )

accuracy_multi(a, b)

tensor(0.8333)

In [ ]:
def accuracy_multi(inp, targ, thresh = 0.5, sigmoid = True):
    if sigmoid: inp = inp.sigmoid()
    return(( inp> thresh) == targ.bool()).float().mean()

In [ ]:
b = tensor ( [[1,1,1], [1,1,1]] )

b.sigmoid()

tensor([[0.7311, 0.7311, 0.7311],
        [0.7311, 0.7311, 0.7311]])

In [ ]:
sigmoid(tensor(1,0))

tensor([0.7311, 0.5000])

In [ ]:
sigmoid( tensor (-5, 0, 5))

tensor([0.0067, 0.5000, 0.9933])

In [ ]:
sigmoid( tensor (-5, 0.001, 5))

tensor([0.0067, 0.5002, 0.9933])

In [ ]:
def accuracy_multi_a(inp, targ, thresh = 0.5, sigmoid = True):
    if sigmoid: inp = inp.sigmoid()
    return( inp)

In [ ]:
a = tensor ( [[1,1,0], [1,1,0]] )
b = tensor ( [[1,1,1], [1,1,1]] )

accuracy_multi_a(a,b)

tensor([[0.7311, 0.7311, 0.5000],
        [0.7311, 0.7311, 0.5000]])

In [ ]:
def accuracy_multi_b(inp, targ, thresh = 0.5, sigmoid = True):
    if sigmoid: inp = inp.sigmoid()
    return( inp> thresh) 

In [ ]:
a = tensor ( [[1,1,0], [1,1,0]] )
b = tensor ( [[1,1,1], [1,1,1]] )

print(accuracy_multi_a(a,b))
print(accuracy_multi_b(a,b))

tensor([[0.7311, 0.7311, 0.5000],
        [0.7311, 0.7311, 0.5000]])
tensor([[ True,  True, False],
        [ True,  True, False]])


In [ ]:
def accuracy_multi_c(inp, targ, thresh = 0.5, sigmoid = True):
    if sigmoid: inp = inp.sigmoid()
    return(( inp> thresh) == targ.bool())

In [ ]:
a = tensor ( [[1,1,0], [1,1,0]] )
b = tensor ( [[1,1,1], [1,1,1]] )

accuracy_multi_c(a,b)

tensor([[ True,  True, False],
        [ True,  True, False]])

In [ ]:
def accuracy_multi_d(inp, targ, thresh = 0.5, sigmoid = True):
    if sigmoid: inp = inp.sigmoid()
    return(( inp> thresh) == targ.bool()).float()

In [ ]:
accuracy_multi_d(a,b)

tensor([[1., 1., 0.],
        [1., 1., 0.]])

In [ ]:
def accuracy_multi(inp, targ, thresh = 0.5, sigmoid = True):
    if sigmoid: inp = inp.sigmoid()
    return(( inp> thresh) == targ.bool()).float().mean()

In [ ]:
accuracy_multi(a,b)

tensor(0.6667)